import "@/app/globals.css"
import { cn } from "@/lib/utils"
import type { Metadata } from "next"
import { Inter as FontSans } from "next/font/google"

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    "flex min-h-screen flex-col bg-slate-100 font-sans antialiased",
                    fontSans.variable,
                )}
            >
                <div className="flex flex-1 items-center justify-center">
                    {children}
                </div>
            </body>
        </html>
    )
}
