import type { Metadata } from "next"
import { Inter as FontSans } from "next/font/google"
import "@/app/globals.css"
import { cn } from "@/lib/utils"
import { FlashToast } from "@/lib/toast"
import Navbar from "./_components/Navbar"
import { Toaster } from "@/components/ui/toaster"

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    "group/bodyTag flex min-h-screen flex-col bg-background font-sans antialiased",
                    fontSans.variable,
                )}
            >
                <Navbar />
                <div className="relative flex flex-1 flex-col items-center">
                    <main className="w-full max-w-[1320px] flex-1 p-6">
                        {children}
                    </main>
                    <div
                        className={`absolute z-[-10] h-full w-full duration-100 group-has-[figure:hover]/bodyTag:z-[100] group-has-[figure:hover]/bodyTag:bg-black/40`}
                    />
                </div>
                <Toaster />
                <FlashToast />
            </body>
        </html>
    )
}
