import type { Metadata } from "next"
import { Inter as FontSans } from "next/font/google"
import "@/app/globals.css"
import { cn } from "@/lib/utils"
import { FlashToast } from "@/lib/toast"
import Navbar from "./_components/Navbar"

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    "group/bodyTag flex min-h-screen flex-col bg-background font-sans antialiased",
                    fontSans.variable,
                )}
            >
                <Navbar />
                <main className="relative flex flex-1 flex-col gap-4">
                    {children}
                    <div
                        className={`absolute z-[100] h-full w-full duration-100 group-has-[figure:hover]/bodyTag:bg-black/40`}
                    />
                </main>
                <FlashToast />
            </body>
        </html>
    )
}
