import type { Metadata } from "next"
import { Inter as FontSans } from "next/font/google"
import "../globals.css"
import { cn } from "@/lib/utils"
import { FlashToast } from "@/lib/toast"
import Navbar from "./seller/_components/Navbar"

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

function SellerLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    fontSans.variable,
                    "flex min-h-screen flex-col bg-background font-sans antialiased",
                )}
            >
                <Navbar />
                <main className="flex flex-1 flex-col gap-4 p-6">
                    {children}
                </main>
            </body>
        </html>
    )
}

export default SellerLayout
